apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-prd-app
  annotations:
    stage: prd
  namespace: t3qtest
  labels:
    app: example-prd-app
spec:
  selector:
    matchLabels:
      app: example-prd-app
  template:
    metadata:
      labels:
        app: example-prd-app
    spec:
      containers:
      - name: test
#        image: kakaobank.harbor.prd/python:3.8-slim
        image: python:3.8-slim
        ports:
        - containerPort: 80
